[package]
name = "chandler-cli"
version = "3.0.1"
authors = ["Forb.Jok <forbjok@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "chandler"
path = "src/main.rs"

[dependencies]
chandler = { path = "../lib" }
chrono = { version = "0.4.19", features = ["serde"] }
ctrlc = "3.2.1"
fern = "0.6.0"
indicatif = "0.16.2"
lazy_static = "1.4.0"
log = "0.4.14"
regex = "1.5.4"
reqwest = { version = "0.11.6", features = ["blocking"] }
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
structopt = "0.3.25"
strum = "0.22.0"
strum_macros = "0.22.0"
toml = "0.5.8"
