[package]
name = "chandler-cli"
version = "3.0.0"
authors = ["Forb.Jok <forbjok@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "chandler"
path = "src/main.rs"

[dependencies]
chandler = { path = "../lib" }
cli_common = { path = "../cli_common" }
chrono = { version = "0.4.19", features = ["serde"] }
ctrlc = "3.1.7"
dirs = "3.0.1"
fern = "0.6.0"
indicatif = "0.15.0"
lazy_static = "1.4.0"
log = "0.4.11"
regex = "1.4.2"
reqwest = { version = "0.10.9", features = ["blocking"] }
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
structopt = "0.3.20"
strum = "0.20.0"
strum_macros = "0.20.1"
toml = "0.5.7"
