[package]
name = "chandler-pcli"
version = "3.0.0"
authors = ["Forb.Jok <forbjok@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chandler = { path = "../lib" }
chrono = { version = "0.4.19", features = ["serde"] }
fern = "0.6.0"
log = "0.4.11"
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
structopt = "0.3.20"
strum = "0.20.0"
strum_macros = "0.20.1"
