[package]
name = "chandler-pcli"
version = "3.0.0"
authors = ["Forb.Jok <forbjok@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chandler = { path = "../lib" }
chrono = { version = "0.4.19", features = ["serde"] }
fern = "0.6.0"
log = "0.4.14"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
structopt = "0.3.25"
strum = "0.22.0"
strum_macros = "0.22.0"
